apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: <+pipeline.variables.image>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DEMO_USERNAME
          value: <+pipeline.variables.username>
        - name: DEMO_PASSWORD
          value: HarnessSecretVariable_dbpassword
