apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: <+pipeline.name>
